### ISSUE TITLE
Website redesign suggestion

### ISSUE THREAD

**Issue by psikoi** [runelite/runelite.net#43]
I've designed a desktop and mobile version of the runelite homepage based on the current homepage.

**Couple of things to notice:**
- I attempted to declutter the homepage, so that a new user will not be overwhelmed by all the links and actions, focusing on the download call-to-action.
- The orange color I chose was based off the fire in the current logo, it is a vibrant color that should attract the user's eyes to important actions and elements of the page.
- Decided to remove the multiple download buttons to include a single button (OS options can be displayed on click by either a dropdown, a popup or anything of the sort), this (again) will make the download action stand out more.
- Grouped the social platforms to the right side of the screen.
- Designed the news as blog posts.

## PS: if accepted, I'd be happy to provide a document with all the measurements, images, colors, fonts, etc.

# Desktop version:

![website mockup](https://user-images.githubusercontent.com/3278148/38270026-179d742c-377a-11e8-9f07-a372b4c537af.png)

# Mobile version:

![mobile website mockup](https://user-images.githubusercontent.com/3278148/38270050-301eca50-377a-11e8-86dd-a2a86e5c9f22.png)

**Comment by deathbeam** [comment]
My thoughts and what can be improved here:

1. Player count needs to be shown somewhere
2. Imo the news functionality from current layout should not be changed, but maybe adding post title and author would be okay
3. Not sure how I feel github being positioned between "Features" and "Blog", seems a bit out of place.
4. The social links on left, mainly the Patreon one will most likely descrease traffic to Patreon itself, but that is probably just because of their terrible logo
5. Stargazers somewhere might be nice, or at least that is what @Adam- wanted to have on home page
6. I don't think I want to change amout of features displayed on home page based on user being on mobile or not

**Comment by psikoi** [comment]
byeee
